//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Shop = newShopTable("public", "shop", "")

type shopTable struct {
	postgres.Table

	// Columns
	ShopID          postgres.ColumnInteger
	UserID          postgres.ColumnInteger
	ShopName        postgres.ColumnString
	ShopDescription postgres.ColumnString
	ShopStatus      postgres.ColumnInteger
	CreatedAt       postgres.ColumnTimez
	UpdatedAt       postgres.ColumnTimez

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ShopTable struct {
	shopTable

	EXCLUDED shopTable
}

// AS creates new ShopTable with assigned alias
func (a ShopTable) AS(alias string) *ShopTable {
	return newShopTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ShopTable with assigned schema name
func (a ShopTable) FromSchema(schemaName string) *ShopTable {
	return newShopTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ShopTable with assigned table prefix
func (a ShopTable) WithPrefix(prefix string) *ShopTable {
	return newShopTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ShopTable with assigned table suffix
func (a ShopTable) WithSuffix(suffix string) *ShopTable {
	return newShopTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newShopTable(schemaName, tableName, alias string) *ShopTable {
	return &ShopTable{
		shopTable: newShopTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newShopTableImpl("", "excluded", ""),
	}
}

func newShopTableImpl(schemaName, tableName, alias string) shopTable {
	var (
		ShopIDColumn          = postgres.IntegerColumn("shop_id")
		UserIDColumn          = postgres.IntegerColumn("user_id")
		ShopNameColumn        = postgres.StringColumn("shop_name")
		ShopDescriptionColumn = postgres.StringColumn("shop_description")
		ShopStatusColumn      = postgres.IntegerColumn("shop_status")
		CreatedAtColumn       = postgres.TimezColumn("created_at")
		UpdatedAtColumn       = postgres.TimezColumn("updated_at")
		allColumns            = postgres.ColumnList{ShopIDColumn, UserIDColumn, ShopNameColumn, ShopDescriptionColumn, ShopStatusColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{UserIDColumn, ShopNameColumn, ShopDescriptionColumn, ShopStatusColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return shopTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ShopID:          ShopIDColumn,
		UserID:          UserIDColumn,
		ShopName:        ShopNameColumn,
		ShopDescription: ShopDescriptionColumn,
		ShopStatus:      ShopStatusColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
