//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Shop struct {
	ShopID          int32 `sql:"primary_key"`
	UserID          int32
	ShopName        string
	ShopDescription string
	ShopStatus      int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
